import { Switch, useTheme } from '@nextui-org/react';
import Head from 'next/head'
import React, { FC } from 'react'

import { Navbar } from '../ui';

interface Props {
  title: string;
}
export const Layout:FC<Props> = ({ children, title}) => {

  

  return (
    <>
      <Head>
        <title>{ title }</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      

      <main>
        { children }
      </main>
    </>
  )
}
