import { Switch, useTheme } from '@nextui-org/react';
import Head from 'next/head'
import React, { FC } from 'react'

import { Navbar } from '../ui';

interface Props {
  title: string;
}
export const Layout:FC<Props> = ({ children, title}) => {

  const origin = (typeof window !== 'undefined') 
                    ? window.location.origin
                    : ''

  

  return (
    <>
      <Head>
        <title>{ title }</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta property="og:title" content={`${title}`} />
        <meta property="og:description" content={`Información de ${title}`} />
        <meta property="og:image" content={`${origin}/img/banner.png`} />
      </Head>

      <Navbar />
      
      <main>
        { children }
      </main>
    </>
  )
}
